name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-proxy:
    name: Build proxy
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build proxy
        working-directory: proxy
        run: |
          msbuild proxy.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x86

      - name: Check artifact
        working-directory: proxy
        shell: pwsh
        run: |
          if (!(Test-Path "Release\RendDX9.dll")) {
            Write-Error "Release\RendDX9.dll not found"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy
          path: proxy/Release/RendDX9.dll
          
  build-speaker:
    name: Build speaker
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build speaker
        working-directory: speaker\cs
        run: dotnet publish -r win-x86 -c Release --self-contained

      - name: Check artifacts
        shell: pwsh
        run: |
          $path = "speaker\cs\bin\Release\net10.0\win-x86\publish"

          $files = @(
            "kbs.dll",
            "ImGuiImpl.dll",
            "cimgui.dll"
          )

          foreach ($file in $files) {
            if (!(Test-Path "$path\$file")) {
              Write-Error "$file was not found"
              exit 1
            }
          }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: speaker
          path: |
            speaker/cs/bin/Release/net10.0/win-x86/publish/kbs.dll
            speaker/cs/bin/Release/net10.0/win-x86/publish/ImGuiImpl.dll
            speaker/cs/bin/Release/net10.0/win-x86/publish/cimgui.dll

  build-underfacility:
    name: Build underfacility
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      # DirectX SDK должен быть установлен до сборки.
      - name: Install DirectX SDK
        shell: pwsh
        run: |
          $url = "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe"
          $installer = "$env:TEMP\DXSDK_Jun10.exe"

          Invoke-WebRequest -Uri $url -OutFile $installer

          Start-Process `
            -FilePath $installer `
            -ArgumentList "/U" `
            -Wait

      - name: Build underfacility
        working-directory: underfacility
        run: |
          msbuild underfacility.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x86

      - name: Check artifact
        working-directory: underfacility
        shell: pwsh
        run: |
          if (!(Test-Path "Release\kbuf.dll")) {
            Write-Error "Release\kbuf.dll not found"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: underfacility
          path: underfacility/Release/kbuf.dll

  build-server:
    name: Build server win64
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.3'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        working-directory: server
        run: |
          poetry install --no-interaction --no-root

      - name: Build Executable
        working-directory: server
        run: |
          poetry run python -m nuitka main.py --mode=onefile --follow-imports --assume-yes-for-downloads --product-name="Kokuban server" --output-filename=kokubanserver-${{ github.event.release.tag_name }}-win64 --product-version=${{ github.event.release.tag_name }} --file-version=${{ github.event.release.tag_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-win64
          path: server/kokubanserver-${{ github.event.release.tag_name }}-win64.exe

  release-server:
    name: Add artifacts server to release
    runs-on: windows-latest
    needs:
      - build-server

    steps:
      - name: Download server win64
        uses: actions/download-artifact@v4
        with:
          name: server-win64
          path: release

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          preserve_order: true
          overwrite_files: true
          fail_on_unmatched_files: true
          files: |
            release/kokubanserver-${{ github.event.release.tag_name }}-win64.exe
          
  release:
    name: Add artifacts to release
    runs-on: windows-latest

    needs:
      - build-proxy
      - build-speaker
      - build-underfacility

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download proxy
        uses: actions/download-artifact@v4
        with:
          name: proxy
          path: release

      - name: Download speaker
        uses: actions/download-artifact@v4
        with:
          name: speaker
          path: release

      - name: Download underfacility
        uses: actions/download-artifact@v4
        with:
          name: underfacility
          path: release

      - name: Copy release files
        shell: pwsh
        run: |
          Copy-Item -Path Roboto-Bold.ttf -Destination release
          Copy-Item -Path Roboto-Regular.ttf -Destination release
          Copy-Item -Path proxy/ORDX9.dll -Destination release

      - name: Archive creation
        shell: pwsh
        working-directory: release
        run: |
          Compress-Archive -Path ./* -DestinationPath kokuban-${{ github.event.release.tag_name }}-win.zip

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          preserve_order: true
          overwrite_files: true
          fail_on_unmatched_files: true
          files: |
            release/kokuban-${{ github.event.release.tag_name }}-win.zip
