name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-proxy:
    name: Build proxy
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build proxy
        working-directory: proxy
        run: |
          msbuild proxy.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x86

      - name: Check artifact
        shell: pwsh
        run: |
          if (!(Test-Path "proxy\RendDX9.dll")) {
            Write-Error "RendDX9.dll was not found"
            exit 1
          }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxy
          path: proxy\RendDX9.dll


  build-speaker:
    name: Build speaker
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build speaker
        working-directory: speaker\cs
        run: dotnet publish -r win-x86 -c Release --self-contained

      - name: Check artifacts
        shell: pwsh
        run: |
          $path = "speaker\cs\bin\Release\net10.0\win-x86\publish"

          $files = @(
            "kbs.dll",
            "ImGuiImpl.dll",
            "cimgui.dll"
          )

          foreach ($file in $files) {
            if (!(Test-Path "$path\$file")) {
              Write-Error "$file was not found"
              exit 1
            }
          }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: speaker
          path: |
            speaker/cs/bin/Release/net10.0/win-x86/publish/kbs.dll
            speaker/cs/bin/Release/net10.0/win-x86/publish/ImGuiImpl.dll
            speaker/cs/bin/Release/net10.0/win-x86/publish/cimgui.dll

  build-underfacility:
    name: Build underfacility
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      # DirectX SDK должен быть установлен до сборки.
      - name: Install DirectX SDK
        shell: pwsh
        run: |
          $url = "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe"
          $installer = "$env:TEMP\DXSDK_Jun10.exe"

          Invoke-WebRequest -Uri $url -OutFile $installer

          Start-Process `
            -FilePath $installer `
            -ArgumentList "/U" `
            -Wait

      - name: Build underfacility
        working-directory: underfacility
        run: |
          msbuild underfacility.vcxproj `
            /p:Configuration=Release `
            /p:Platform=x86

      - name: Check artifact
        shell: pwsh
        run: |
          if (!(Test-Path "underfacility\kbuf.dll")) {
            Write-Error "kbuf.dll was not found"
            exit 1
          }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: underfacility
          path: underfacility\kbuf.dll

  release:
    name: Add artifacts to release
    runs-on: windows-latest

    needs:
      - build-proxy
      - build-speaker
      - build-underfacility

    steps:
      - name: Download proxy
        uses: actions/download-artifact@v4
        with:
          name: proxy
          path: release

      - name: Download speaker
        uses: actions/download-artifact@v4
        with:
          name: speaker
          path: release

      - name: Download underfacility
        uses: actions/download-artifact@v4
        with:
          name: underfacility
          path: release

      - name: Add files to release
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" `
            release\RendDX9.dll `
            release\kbs.dll `
            release\ImGuiImpl.dll `
            release\cimgui.dll `
            release\kbuf.dll `
            --clobber
